id: A8A15BC20
title: 'The Source of Accomplishment, the Fruit of the Twofold Truth: A Prayer to
  the Wisdom Ḍākinī Dechen Gyalmo'
type: translation
pechas:
- I64667A6D
- I433B2952
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:43:53.941974
  last_modified_at: 2023-01-04 11:43:53.941981
  collections:
  - Dodrupchen Jigme Trinle Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  I64667A6D/31B1: B3B3
  I433B2952/E897: B3B3
